Repository iMicknl/ha-tahoma, pull requests merged in 2020-10, with the labels that each got.

#286 Remove unused imports
  custom_components/tahoma/__init__.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/sensor.py
Labels: enhancement

#280 Improve error handling on startup
  custom_components/tahoma/__init__.py
  custom_components/tahoma/coordinator.py
Labels: enhancement

#276 Only remove update listener when unload was succesfull
  custom_components/tahoma/__init__.py
Labels: enhancement

#287 Fix pylint warnings
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/services.yaml
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_device.py
  tests/test_config_flow.py
Labels: enhancement

#263 Support cancelling cover movement when initiated outside Home Assistant
  custom_components/tahoma/cover.py
Labels: enhancement

#288 Use round() instead of int()
  custom_components/tahoma/__init__.py
  custom_components/tahoma/light.py
Labels: enhancement

#290 Improve debug logging in DataUpdateCoordinator
  custom_components/tahoma/coordinator.py
Labels: enhancement

#295 added CORE_SLATE_ORIENTATION_STATE
  custom_components/tahoma/cover.py
Labels: bug

#293 Reverse open/close for all Awning devices
  custom_components/tahoma/cover.py
Labels: bug, platform: cover

#308 Add dev container to ease development
  .devcontainer/README.md
  .devcontainer/configuration.yaml
  .devcontainer/devcontainer.json
  .vscode/tasks.json
  custom_components/tahoma/__init__.py
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/scene.py
  custom_components/tahoma/tahoma_device.py
  setup.cfg
Labels: enhancement

#310 Update hacs.json
  hacs.json
Labels: enhancement

#309 Update pre-commit version
  .devcontainer/configuration.yaml
  .devcontainer/devcontainer.json
  .gitattributes
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/hassfest.yml
  .github/workflows/linters.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .vscode/tasks.json
  custom_components/tahoma/__init__.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/services.yaml
  tests/test_config_flow.py
Labels: enhancement

#306 Improve handling of errors when Somfy server is in maintenance.
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/strings.json
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/fr.json
  custom_components/tahoma/translations/nl.json
  requirements.test.txt
Labels: enhancement

#311 Fix auto / manual mode detection on Somfy's Smart Thermostat.
  custom_components/tahoma/climate_devices/somfy_thermostat.py
Labels: bug

#281 Add support for AtlanticPassAPCDHW (WaterHeatingSystem)
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/atlantic_pass_apcdhw.py
  custom_components/tahoma/const.py
Labels: feature, platform: climate
