Repository iMicknl/ha-tahoma, pull requests merged in 2020-12, with the labels that each got.

#316 Implement Coordinator entity
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#318 Print HomeKit code in log while in debug mode
  README.md
  custom_components/tahoma/__init__.py
Labels: feature

#325 Fix wrong position for awning valance
  custom_components/tahoma/cover.py
Labels: bug

#326 Fixed a typo
  custom_components/tahoma/translations/fr.json
Labels: bug

#329 Use existing web session
  custom_components/tahoma/__init__.py
Labels: enhancement
