Repository iMicknl/ha-tahoma, pull requests merged in 2020-09, with the labels that each got.

#250 Moved climate devices files to their own directory.
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/__init__.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/dimmer_exterior_heating.py
  custom_components/tahoma/climate_devices/somfy_thermostat.py
Labels: enhancement

#227 Improve entity update after command execution, add retry logic
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/strings.json
  custom_components/tahoma/tahoma_device.py
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/fr.json
  custom_components/tahoma/translations/nl.json
  requirements.test.txt
Labels: enhancement

#242 Add service to set cover position with low speed
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/services.yaml
Labels: feature

#247 Add support for DomesticHotWaterTank
  custom_components/tahoma/const.py
  custom_components/tahoma/switch.py
Labels: feature

#244 Add support for StatelessExteriorHeating device.
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/const.py
Labels: feature, platform: climate

#257 Rename UNIT_PERCENTAGE to PERCENTAGE (ha version 0.115)
  custom_components/tahoma/sensor.py
Labels: bug

#251 Improve `stop` and `stop tilt` command for covers
  custom_components/tahoma/__init__.py
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/scene.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_device.py
  requirements.test.txt
Labels: enhancement, platform: cover

#262 Handle exceptions in execution of commands
  custom_components/tahoma/manifest.json
  custom_components/tahoma/tahoma_device.py
  requirements.test.txt
Labels: bug

#260 Read model and manufacturer from state
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#267 Add a tick box to ensure users have read the readme to the end.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/unsupported-device.md
Labels: enhancement

#272 Add unit tests for option flow
  custom_components/tahoma/coordinator.py
  tests/test_config_flow.py
Labels: enhancement

#274 Update HACS validation to pull from main..
  .github/workflows/validate.yml
Labels: Meta: Exclude From Changelog

#273 Change CookieJar to use defaults (unsafe=False)
  custom_components/tahoma/__init__.py
Labels: enhancement

#270 Strongly type the event types in DataUpdateCoordinator.
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
  requirements.test.txt
Labels: enhancement
