Repository iMicknl/ha-tahoma, pull requests merged in 2020-07, with the labels that each got.

#93 Remove the lock on apply_action
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_device.py
Labels: Needs Testing, bug

#95 Re-log in the API after a "error":"Not authenticated"
  .gitignore
  CHANGELOG.md
  custom_components/tahoma/tahoma_api.py
Labels: bug

#101 Remove exception raising in Device `__init__` in the API
  custom_components/tahoma/tahoma_api.py
Labels: bug, enhancement

#109 Update README.md
  README.md
Labels: documentation

#84 Add support for more sensors & basic Siren (switch) support
  README.md
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/const.py
  custom_components/tahoma/scene.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
Labels: enhancement, platform: binary_sensor, platform: sensor, platform: switch

#108 Remove lock variables from Cover device state attributes
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
Labels: enhancement, platform: cover

#116 Parse temperature unit for TemperatureSensor
  custom_components/tahoma/const.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/tahoma_api.py
Labels: enhancement, platform: sensor

#125 Move constants outside of const.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#127 Remove api doc from this repository
  tahoma_api_doc/CallableNames.txt
  tahoma_api_doc/apiDocDyn.js
  tahoma_api_doc/apiDocStyle.css
  tahoma_api_doc/jquery-1.10.2-ui.js
  tahoma_api_doc/jquery-1.10.2.js
  tahoma_api_doc/tahoma_api.html
Labels: Meta: Exclude From Changelog

#132 Modified changelog workflow
  .github/pr-labeler.yml
  .github/workflows/black.yml
  .github/workflows/changelog.yaml
  .github/workflows/changelog.yml
  .github/workflows/hassfest.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/validate.yml
Labels: Meta: Exclude From Changelog

#133 Remove ADMIN_GITHUB_TOKEN
  .github/workflows/release-drafter.yml
Labels: Meta: Exclude From Changelog

#126 Add constants for all strings
  custom_components/tahoma/__init__.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#136 Fix light update failing.
  custom_components/tahoma/light.py
Labels: bug

#138 fix cover set up
  custom_components/tahoma/cover.py
Labels: bug

#137 fix lock set up
  custom_components/tahoma/lock.py
Labels: bug

#139 fix changlog workflow trigger.
  .github/workflows/changelog.yml
Labels: bug

#140 fix changlog workflow trigger.
  .github/workflows/changelog.yml
Labels: Meta: Exclude From Changelog, bug

#142 Fix command and state definitions being incorrectly set in the API
  custom_components/tahoma/tahoma_api.py
Labels: bug

#143 Remove .format().
  custom_components/tahoma/sensor.py
Labels: enhancement

#144 Move forgotten icons to constants.
  custom_components/tahoma/switch.py
Labels: enhancement

#148 Add helper functions select_command and select_state
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#153 Add support for 'screen' uiClass.
  custom_components/tahoma/const.py
Labels: bug

#154 Remove return from `apply_action`
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#147 Add cycle support for the cover platform
  custom_components/tahoma/cover.py
Labels: enhancement

#156 Fix should_wait return value
  custom_components/tahoma/tahoma_device.py
Labels: bug

#157 Return None when no position state
  custom_components/tahoma/cover.py
Labels: bug

#158 Fix rescheduling update.
  custom_components/tahoma/tahoma_device.py
Labels: bug

#162 Fix/fix 161
  custom_components/tahoma/climate_deh.py
Labels: bug

#159 Enhancement/refactor climate
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_aeh.py
  custom_components/tahoma/climate_deh.py
  custom_components/tahoma/climate_st.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
Labels: breaking, enhancement

#165 Position is incorrectly inverted when 0 because bool(0) == False.
  custom_components/tahoma/cover.py
Labels: bug, platform: cover

#164 Round float state to 2 digits.
  custom_components/tahoma/sensor.py
Labels: bug, platform: climate

#166 Update README.md with ExteriorHeatingSystem support.
  README.md
Labels: documentation

#160 Make all functions async, utilise new Python wrapper, better exception handling, improved device mapping
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/scene.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_api.py
  custom_components/tahoma/tahoma_device.py
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/nl.json
Labels: enhancement

#171 Add support for SwimmingPool devices
  custom_components/tahoma/const.py
Labels: enhancement

#169 Simplify logic for RTS devices
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#170 Improve support for GasSensor, ThermalEnergySensor, WaterSensor and add support for Siren Status
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/const.py
  custom_components/tahoma/sensor.py
Labels: enhancement

#168 Add more ui_classes and sort them alphabetically
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/const.py
  custom_components/tahoma/sensor.py
Labels: enhancement

#176 Fix execute_command call
  custom_components/tahoma/tahoma_device.py
Labels: bug

#178 Fix assumed state
  custom_components/tahoma/tahoma_device.py
Labels: bug

#180 Add device attributes to attributes
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#177 Fix how the unit of measurement is retrieved
  custom_components/tahoma/sensor.py
Labels: bug

#172 Return unknown if position is over 100
  custom_components/tahoma/cover.py
Labels: bug

#182 Add missing states for some sensor and binary sensor devices
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/sensor.py
Labels: enhancement

#183 Update implementation for Siren
  custom_components/tahoma/switch.py
Labels: enhancement

#184 Fix cover implementation for devices with only cycle command
  custom_components/tahoma/cover.py
Labels: bug

#187 Rewrite climate component to async approach
  custom_components/tahoma/climate_aeh.py
  custom_components/tahoma/climate_deh.py
  custom_components/tahoma/climate_st.py
Labels: bug

#188 Update GitHub issue templates and README
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/unsupported-device.md
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/manifest.json
Labels: Meta: Exclude From Changelog, enhancement

#189 Change default update interval from 30 seconds to 5
  custom_components/tahoma/__init__.py
Labels: Meta: Exclude From Changelog, bug

#190 Pin pyhoma package and change tahoma_api to pyhoma
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/scene.py
  custom_components/tahoma/tahoma_device.py
Labels: enhancement

#192 Enable position for AdjustableSlatsRollerShutter devices
  custom_components/tahoma/cover.py
Labels: enhancement, platform: cover

#194 Add bot to mark stale issues and pull requests
  .github/workflows/stale.yml
Labels: Meta: Exclude From Changelog, enhancement

#195 Remove SCAN_INTERVAL in favour of DataUpdateCoordinator
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/sensor.py
Labels: enhancement

#196 Fix missing client for scene
  custom_components/tahoma/__init__.py
  custom_components/tahoma/scene.py
Labels: bug

#198 Reduce platform setup complexity
  custom_components/tahoma/__init__.py
  custom_components/tahoma/const.py
Labels: enhancement

#199 Various small clean
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/tahoma_device.py
Labels: enhancement
