Repository iMicknl/ha-tahoma, pull requests merged in 2020-08, with the labels that each got.

#200 Create constant for ignored devices
  custom_components/tahoma/__init__.py
  custom_components/tahoma/const.py
Labels: enhancement

#202 Update README for HACS
  README.md
Labels: Meta: Exclude From Changelog

#201 Support YAML configuration
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
Labels: enhancement

#203 Some states are missing at init in tahoma's response
  custom_components/tahoma/climate_st.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
Labels: bug

#197 Improve climate platform and support dynamic state allocation
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_st.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
Labels: enhancement

#209 Match climate devices on their widgetName
  custom_components/tahoma/const.py
Labels: bug

#210 Bump pyhoma to 0.3.2
  custom_components/tahoma/manifest.json
Labels: bug

#224 Support opening and closing the cover of MyFoxSecurityCamera
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
Labels: enhancement, platform: cover

#232 Fix crash when using faulty / disabled ZWave devices
  README.md
  custom_components/tahoma/manifest.json
Labels: bug

#213 Add first unit tests for Config Flow
  .github/workflows/hassfest.yml
  .github/workflows/matchers/python.json
  .github/workflows/test.yml
  custom_components/tahoma/config_flow.py
  requirements.test.txt
  requirements.txt
  tests/__init__.py
  tests/common.py
  tests/test_config_flow.py
Labels: enhancement

#214 Add alarm integration
  README.md
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/const.py
Labels: enhancement, platform: alarm_control_panel

#236 Add `my` service for light and cover devices
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/services.yaml
Labels: enhancement

#237 Add custom session, handle HTTP_CONNECT_ERRORS and retry on ServerDisconnectedError
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/manifest.json
  requirements.test.txt
  tests/test_config_flow.py
Labels: enhancement

#243 Remove auto changelog as it looks messy and unreliable.
  .github/workflows/changelog.yml
Labels: Meta: Exclude From Changelog, enhancement
