Repository iMicknl/ha-tahoma, pull requests merged in 2021-01, with the labels that each got.

#335 Change MIN_UPDATE_INTERVAL
  custom_components/tahoma/const.py
Labels: bug

#327 Support 'suddenDropMode' state for Somfy Thermostat
  custom_components/tahoma/climate_devices/somfy_thermostat.py
Labels: bug

#336 Clean up code for climate devices
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/dimmer_exterior_heating.py
Labels: bug

#338 Use constant for source
  custom_components/tahoma/__init__.py
Labels: bug

#332 Support Cozytouch, Rexel and Connexoon RTS.
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/strings.json
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/fr.json
  custom_components/tahoma/translations/nl.json
  tests/test_config_flow.py
Labels: feature

#348 fix bug in hvac modes introduced in #336
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
Labels: bug

#347 Add additional Overkiz API's (Hi Kumo, eedomus)
  custom_components/tahoma/const.py
Labels: feature

#346 Catch timeout error in DataUpdateCoordinator
  custom_components/tahoma/coordinator.py
Labels: bug

#317 Add support for obstruction detected for HomeKit
  custom_components/tahoma/cover.py
Labels: enhancement

#342 Make 'execute_command' service an admin service
  custom_components/tahoma/__init__.py
Labels: bug

#359 Fix for sensors returning 'unknown' when value is exactly 0
  custom_components/tahoma/sensor.py
Labels: bug

#361 Fix Hi-Kumo server URL
  custom_components/tahoma/const.py
Labels: bug

#353 Add support for DomesticHotWaterProduction
  custom_components/tahoma/const.py
  custom_components/tahoma/water_heater.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
Labels: feature, platform: water_heater

#363 Update README to reflect support of other OverKiz hubs
  README.md
Labels: enhancement

#333 Add gateways to Device Registry
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/tahoma_device.py
  requirements.test.txt
Labels: feature

#365 Add service to retrieve execution history
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/services.yaml
  requirements.test.txt
Labels: feature

#366 Remove duplicate code
  custom_components/tahoma/__init__.py
Labels: bug
