Repository iMicknl/ha-tahoma, pull requests merged in 2021-08, with the labels that each got.

#501 Fix for breaking changes in core for Ampere/Volt sensors
  custom_components/tahoma/sensor.py
Labels: bug

#492 Remove unsupported command for AtlanticPassAPCHeatingAndCoolingZone
  custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py
Labels: bug

#494 Added German translation
  custom_components/tahoma/translations/de.json
Labels: enhancement

#418 Refactor supported hubs/servers and load them from pyhoma
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/manifest.json
  requirements.txt
  tests/test_config_flow.py
Labels: enhancement

#511 Temporary bugfix for AwningValance (until this is fixed serverside)
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/awning.py
  custom_components/tahoma/cover_devices/vertical_cover.py
Labels: bug

#505 Add binary sensors dynamically based on available device state
  custom_components/tahoma/__init__.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/const.py
Labels: enhancement, breaking

#425 Add sensors dynamically based on available device state
  custom_components/tahoma/__init__.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/tahoma_entity.py
  hacs.json
  requirements_dev.txt
  requirements_test.txt
Labels: breaking, feature

#506 Split entity between entity and executor logic [refactor]
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py
  custom_components/tahoma/climate_devices/atlantic_electrical_towel_dryer.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_zone_control.py
  custom_components/tahoma/climate_devices/atlantic_pass_apcdhw.py
  custom_components/tahoma/climate_devices/dimmer_exterior_heating.py
  custom_components/tahoma/climate_devices/evo_home_controller.py
  custom_components/tahoma/climate_devices/heating_set_point.py
  custom_components/tahoma/climate_devices/hitachi_air_to_air_heat_pump.py
  custom_components/tahoma/climate_devices/hitachi_air_to_water_heating_zone.py
  custom_components/tahoma/climate_devices/somfy_thermostat.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/awning.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/cover_devices/vertical_cover.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/executor.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_entity.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
  custom_components/tahoma/water_heater_devices/hitachi_dhw.py
Labels: enhancement

#512 Improve code quality for description entity
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/sensor.py
Labels: enhancement

#518 Don't error on missing hub information, for old Config Flow entries
  custom_components/tahoma/__init__.py
Labels: bug

#523 Fix current temperature retrieval for climate devices
  custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py
  custom_components/tahoma/climate_devices/somfy_thermostat.py
  custom_components/tahoma/sensor.py
Labels: bug

#524 Improve error handling in coordinator (during BadCredentials error)
  custom_components/tahoma/coordinator.py
Labels: enhancement

#528 Fix for binary sensors
  custom_components/tahoma/binary_sensor.py
Labels: bug

#530 Bump to 2.6.3
  custom_components/tahoma/manifest.json
Labels: Meta: Exclude From Changelog

#531 Add TaHoma switch instructions
  README.md
Labels: documentation

#497 Add low speed switch entity
  custom_components/tahoma/__init__.py
  custom_components/tahoma/cover_devices/vertical_cover.py
  custom_components/tahoma/switch.py
Labels: enhancement, platform: cover

#520 Add DHCP discovery to Config Flow
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/manifest.json
  requirements_test.txt
  tests/test_config_flow.py
Labels: feature

#535 Rename constants to Overkiz
  custom_components/tahoma/__init__.py
  custom_components/tahoma/const.py
Labels: enhancement

#534 Rename TahomaDataUpdateCoordinator to OverkizDataUpdateCoordinator
  .devcontainer/devcontainer.json
  custom_components/tahoma/__init__.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py
  custom_components/tahoma/climate_devices/dimmer_exterior_heating.py
  custom_components/tahoma/climate_devices/somfy_thermostat.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/executor.py
  custom_components/tahoma/light.py
Labels: enhancement

#536 Rename all platforms to Overkiz
  custom_components/tahoma/__init__.py
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/awning.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/cover_devices/vertical_cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/scene.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/water_heater.py
Labels: enhancement

#537 Fix merge issue in switch after GitHub merge
  custom_components/tahoma/switch.py
Labels: bug

#539 Migrate to class attributes
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py
  custom_components/tahoma/climate_devices/atlantic_electrical_towel_dryer.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_zone_control.py
  custom_components/tahoma/climate_devices/atlantic_pass_apcdhw.py
  custom_components/tahoma/climate_devices/dimmer_exterior_heating.py
  custom_components/tahoma/climate_devices/evo_home_controller.py
  custom_components/tahoma/climate_devices/heating_set_point.py
  custom_components/tahoma/climate_devices/hitachi_air_to_air_heat_pump.py
  custom_components/tahoma/climate_devices/hitachi_air_to_water_heating_zone.py
  custom_components/tahoma/climate_devices/somfy_thermostat.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/cover_devices/awning.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/scene.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
  custom_components/tahoma/water_heater_devices/hitachi_dhw.py
Labels: enhancement

#529 Rebrand integration name to Overkiz (by Somfy) and change descriptions
  README.md
  custom_components/tahoma/manifest.json
  custom_components/tahoma/strings.json
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/fr.json
  custom_components/tahoma/translations/nl.json
Labels: enhancement

#541 Small README improvements
  README.md
  hacs.json
Labels: documentation

#533 Handle device created / updated / removed event in DataUpdateCoordinator
  custom_components/tahoma/__init__.py
  custom_components/tahoma/coordinator.py
Labels: enhancement

#543 Add discord link
  README.md
Labels: documentation

#545 Add support for priority lock
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/sensor.py
Labels: enhancement
