Repository iMicknl/ha-tahoma, pull requests merged in 2021-10, with the labels that each got.

#561 Remove polling custom interval and reduce it for stateless configuration
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/strings.json
  custom_components/tahoma/translations/de.json
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/fr.json
  custom_components/tahoma/translations/nl.json
  tests/test_config_flow.py
Labels: feature

#578 Update awning detection
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
Labels: bug, breaking

#636 Create a new client session to allow multiple hubs on the same server
  custom_components/tahoma/__init__.py
Labels: bug

#638 Move overkiz.event to the end of the `coordinator` logic
  custom_components/tahoma/coordinator.py
Labels: enhancement

#633 Bump pyhoma to 0.6.3
  custom_components/tahoma/__init__.py
  custom_components/tahoma/manifest.json
Labels: bug

#637 Add more state sensors for DomesticHotWaterProduction
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/sensor.py
Labels: bug
