Repository iMicknl/ha-tahoma, pull requests merged in 2021-05, with the labels that each got.

#421 Fix GitHub actions
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: Meta: Exclude From Changelog, bug

#436 Don't run the tests on python 3.7 anymore
  .github/workflows/test.yml
Labels: Meta: Exclude From Changelog

#437 Update pre-commit hooks
  .devcontainer/devcontainer.json
  .pre-commit-config.yaml
  custom_components/tahoma/manifest.json
  requirements.txt
  setup.cfg
Labels: Meta: Exclude From Changelog, enhancement

#440 Restrict Deploy commands/states to awning
  custom_components/tahoma/cover.py
Labels: Meta: Exclude From Changelog, bug

#444 Fix broken tests
  .devcontainer/devcontainer.json
  .github/workflows/test.yml
  .vscode/launch.json
  .vscode/settings.json
  custom_components/__init__.py
  requirements.test.txt
  requirements.txt
  requirements_dev.txt
  requirements_test.txt
  tests/common.py
  tests/conftest.py
  tests/test_config_flow.py
Labels: bug

#449 Remove code dedicated to gate opener
  custom_components/tahoma/cover.py
Labels: enhancement

#438 fixes for "Add support for AtlanticHeatRecoveryVentilation"
  custom_components/tahoma/climate_devices/atlantic_heat_recovery_ventilation.py
Labels: feature

#451 Update Pyhoma to 0.5.15
  custom_components/tahoma/manifest.json
  requirements.txt
Labels: enhancement

#408 fixes for "Add support for AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint"
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/manifest.json
Labels: enhancement

#455 Remove setPosition
  custom_components/tahoma/cover.py
Labels: enhancement
