Repository iMicknl/ha-tahoma, pull requests merged in 2021-07, with the labels that each got.

#473 Update pyhoma and require the latest Home Assistant version
  custom_components/tahoma/manifest.json
  hacs.json
  requirements.txt
Labels: enhancement

#464 Fix is_opening/closing for RTS devices
  custom_components/tahoma/cover.py
  custom_components/tahoma/tahoma_entity.py
Labels: bug

#452 Improve reauth, Config Flow and error handling
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/strings.json
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/fr.json
  custom_components/tahoma/translations/nl.json
  requirements_dev.txt
  requirements_test.txt
  tests/conftest.py
  tests/test_config_flow.py
Labels: enhancement

#474 Add more information regarding Model and Manufacturer
  custom_components/tahoma/tahoma_entity.py
Labels: enhancement

#454 Adjust Atlantic Electrical Heater to new standards and fix issues
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
Labels: bug

#423 Add support for AtlanticElectricalTowelDryer
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/atlantic_electrical_towel_dryer.py
  custom_components/tahoma/const.py
Labels: feature

#362 Adds basic support for AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py
  custom_components/tahoma/const.py
Labels: feature

#380 Add basic support for AtlanticPassAPCHeatingAndCoolingZone
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_zone_control.py
  custom_components/tahoma/const.py
Labels: blocked, feature

#364 Add basic support for HitachiAirToAirHeatPump
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/hitachi_air_to_air_heat_pump.py
  custom_components/tahoma/const.py
  custom_components/tahoma/tahoma_entity.py
Labels: feature

#475 Update issue reports to use GitHub template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/unsupported-device.md
  .github/ISSUE_TEMPLATE/unsupported_device.yml
  .github/workflows/stale.yml
  .yamllint
Labels: Meta: Exclude From Changelog

#477 List available services
  README.md
Labels: documentation

#482 fix a typo.
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
Labels: bug

#488 Fix io:DiscreteGateOpenerIOComponent
  custom_components/tahoma/cover.py
Labels: bug

#480 Improve typing for `async_setup_entry`
  custom_components/tahoma/__init__.py
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/scene.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/water_heater.py
Labels: enhancement

#495 Add Open with VScode badge
  README.md
Labels: documentation

#490 Split cover.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/awning.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/cover_devices/vertical_cover.py
Labels: enhancement

#496 Add My Home Assistant button to README
  README.md
Labels: documentation

#499 Bump pyhoma to 0.5.17
  custom_components/tahoma/manifest.json
  requirements.txt
Labels: enhancement
