Repository iMicknl/ha-tahoma, pull requests merged in 2021-02, with the labels that each got.

#368 Improve issue templates, adding the Hub used
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/unsupported-device.md
Labels: enhancement

#371 Fix exception when using Home Protect System hub
  custom_components/tahoma/manifest.json
  requirements.test.txt
Labels: bug

#343 Group entities by physical device
  custom_components/tahoma/__init__.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/tahoma_device.py
Labels: feature

#374 Fix exception when using Somfy TaHoma v1 hub
  custom_components/tahoma/manifest.json
  requirements.test.txt
Labels: enhancement

#375 Fix reversed position for AwningValance covers
  custom_components/tahoma/cover.py
Labels: bug

#384 Improve support for other hubs (e.g. Hi Kumo)
  custom_components/tahoma/__init__.py
  custom_components/tahoma/const.py
  custom_components/tahoma/manifest.json
  requirements.test.txt
Labels: enhancement

#388 Fix exception for devices who return JSON_ARRAY/JSON.OBJECT as state
  custom_components/tahoma/coordinator.py
Labels: bug

#385 Code quality improvements based on core feedback
  custom_components/tahoma/__init__.py
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/atlantic_pass_apcdhw.py
  custom_components/tahoma/climate_devices/dimmer_exterior_heating.py
  custom_components/tahoma/climate_devices/somfy_thermostat.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/scene.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/tahoma_entity.py
  custom_components/tahoma/water_heater.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
Labels: enhancement

#393 Fix bugs introduced by core feedback PR
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/atlantic_pass_apcdhw.py
  custom_components/tahoma/climate_devices/dimmer_exterior_heating.py
  custom_components/tahoma/climate_devices/somfy_thermostat.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/light.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
Labels: bug
