Repository iMicknl/ha-tahoma, pull requests merged in 2021-04, with the labels that each got.

#414 Update Pyhoma to 0.5.10
  custom_components/tahoma/manifest.json
  requirements.test.txt
Labels: enhancement

#416 Check for 'unavailable' while updating temperature sensor in Climate device
  custom_components/tahoma/climate_devices/somfy_thermostat.py
Labels: bug

#422 Fix get execution history for CozyTouch devices
  custom_components/tahoma/manifest.json
  requirements.test.txt
Labels: bug

#405 Add support for EvoHomeController
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/evo_home_controller.py
  custom_components/tahoma/const.py
Labels: feature

#417 Speed up boot, by gathering async tasks.
  custom_components/tahoma/__init__.py
Labels: feature

#426 Reduce battery state complexity
  custom_components/tahoma/tahoma_entity.py
Labels: enhancement

#424 Fix 'execute_command' service
  custom_components/tahoma/__init__.py
  custom_components/tahoma/services.yaml
Labels: bug

#432 Add support for RTSGeneric covers
  custom_components/tahoma/const.py
Labels: bug

#433 Bump pyhoma to 0.5.12
  custom_components/tahoma/manifest.json
  requirements.test.txt
Labels: bug
