Repository iMicknl/ha-tahoma, pull requests merged in 2021-09, with the labels that each got.

#540 Clean up entity model, remove extra states and attributes
  custom_components/tahoma/entity.py
Labels: enhancement

#549 Use STATE_CLASS_TOTAL_INCREASING
  custom_components/tahoma/sensor.py
  hacs.json
Labels: bug

#550 Migrate to native unit of measurement
  custom_components/tahoma/entity.py
  custom_components/tahoma/sensor.py
Labels: bug

#552 Fix hvac_modes for Hitachi Air To Water
  custom_components/tahoma/climate_devices/hitachi_air_to_water_heating_zone.py
Labels: bug

#553 Migrate to native unit of measurement (again)
  custom_components/tahoma/sensor.py
Labels: bug

#555 Fix NoneType object is not iterable when there is no cover
  custom_components/tahoma/switch.py
Labels: bug

#556 Add My Position sensor
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/sensor.py
Labels: enhancement

#559 Update main image
  README.md
  media/tahoma_device_page.png
Labels: Meta: Exclude From Changelog

#558 Update supported devices section
  README.md
Labels: documentation

#567 Update Discord link to a never expiring invite
  README.md
Labels: bug

#570 Update codeowners
  README.md
  custom_components/tahoma/manifest.json
Labels: Meta: Exclude From Changelog

#575 Bump version to 2.8.0
  custom_components/tahoma/manifest.json
Labels: Meta: Exclude From Changelog

#542 Add sensor for Discrete RSSI Level (disabled by default)
  custom_components/tahoma/sensor.py
Labels: enhancement

#571 Enhance logging details
  custom_components/tahoma/__init__.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
Labels: enhancement

#581 Add HomeKit Setup Code sensor (disabled by default)
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/sensor.py
Labels: feature

#584 Redact gateway information in logging
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/unsupported_device.yml
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  requirements.txt
  requirements_dev.txt
  requirements_test.txt
Labels: enhancement

#573 Trigger event on failure
  README.md
  custom_components/tahoma/coordinator.py
Labels: enhancement
