Repository iMicknl/ha-tahoma, pull requests merged in 2021-11, with the labels that each got.

#641 Fix number entity when state is None
  custom_components/tahoma/number.py
Labels: bug

#611 Support for entity categories, configuration URL and other 2021.11 related features
  custom_components/tahoma/entity.py
  custom_components/tahoma/number.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  hacs.json
  requirements_dev.txt
  requirements_test.txt
Labels: enhancement

#645 Add configuration URL to gateway
  custom_components/tahoma/__init__.py
Labels: enhancement

#631 Gitpod
  .gitpod.Dockerfile
  .gitpod.yml
Labels: Meta: Exclude From Changelog

#656 Bump pyhoma to 0.6.4
  custom_components/tahoma/manifest.json
  requirements.txt
Labels: enhancement

#642 Improve select entity and add support for setting Simple Memorized Volume
  custom_components/tahoma/const.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/select.py
Labels: feature

#658 Look for open closed state first
  custom_components/tahoma/cover_devices/tahoma_cover.py
Labels: bug
