Repository iMicknl/ha-tahoma, pull requests merged in 2021-12, with the labels that each got.

#639 Remove deprecated code (`yaml` flow, migration from config flow 1)
  custom_components/tahoma/__init__.py
  custom_components/tahoma/config_flow.py
  tests/test_config_flow.py
Labels: enhancement, breaking

#666 Replace extra_state_attributes
  custom_components/tahoma/cover_devices/tahoma_cover.py
Labels: bug

#613 Change constants to centralized enum
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/hitachi_air_to_air_heat_pump.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/awning.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/cover_devices/vertical_cover.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/number.py
  custom_components/tahoma/select.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/water_heater.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
  custom_components/tahoma/water_heater_devices/hitachi_dhw.py
  requirements.txt
  requirements_dev.txt
  requirements_test.txt
Labels: enhancement

#668 Enhancements for 2021.12.0 update
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/number.py
  custom_components/tahoma/select.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/water_heater.py
  hacs.json
  requirements_dev.txt
  requirements_test.txt
  tests/test_config_flow.py
Labels: enhancement

#538 Move Siren devices from Switch to Siren entity
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/executor.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/siren.py
  custom_components/tahoma/switch.py
  requirements.txt
Labels: enhancement, breaking

#647 Migrate `my` service to button entity, and add other stateless buttons
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/button.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/const.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/light.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/number.py
  custom_components/tahoma/select.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/services.yaml
  hacs.json
Labels: breaking, feature

#686 Add autoMode parameter to DomesticHotWaterProduction
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
Labels: bug

#685 Fix Executor bug that happens for Python 3.8 installations
  custom_components/tahoma/executor.py
Labels: bug

#691 Use get_setup() endpoint instead of 3 seperate API calls
  custom_components/tahoma/__init__.py
Labels: enhancement

#690 Move to PyOverkiz
  README.md
  custom_components/tahoma/__init__.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/hitachi_air_to_air_heat_pump.py
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/const.py
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/awning.py
  custom_components/tahoma/cover_devices/tahoma_cover.py
  custom_components/tahoma/cover_devices/vertical_cover.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/executor.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/number.py
  custom_components/tahoma/scene.py
  custom_components/tahoma/select.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/siren.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/water_heater.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
  custom_components/tahoma/water_heater_devices/hitachi_dhw.py
  requirements.txt
  tests/test_config_flow.py
Labels: enhancement
