Repository iMicknl/ha-tahoma, pull requests merged in 2022-02, with the labels that each got.

#746 feat: Atlantic DHWP MLB support
  custom_components/tahoma/sensor.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
Labels: feature

#744 Backport Number platform from Core
  .github/workflows/test.yml
  custom_components/tahoma/__init__.py
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/button.py
  custom_components/tahoma/climate.py
  custom_components/tahoma/cover.py
  custom_components/tahoma/entity.py
  custom_components/tahoma/light.py
  custom_components/tahoma/lock.py
  custom_components/tahoma/number.py
  custom_components/tahoma/scene.py
  custom_components/tahoma/select.py
  custom_components/tahoma/sensor.py
  custom_components/tahoma/siren.py
  custom_components/tahoma/switch.py
  custom_components/tahoma/water_heater.py
  hacs.json
  requirements_dev.txt
  requirements_test.txt
  tests/test_config_flow.py
Labels: enhancement

#748 upgrade python version in gitpod.
  .gitpod.Dockerfile
  .gitpod.yml
Labels: enhancement, Meta: Exclude From Changelog

#747 Add gateway_id to the config flow title.
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/strings.json
  custom_components/tahoma/translations/en.json
  custom_components/tahoma/translations/fr.json
  tests/test_config_flow.py
Labels: enhancement

#750 Fix core detection when overkiz is ignored
  custom_components/tahoma/__init__.py
Labels: bug

#751 Backport Cover plaform from Core
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_devices/vertical_cover.py
  custom_components/tahoma/cover_entities/awning.py
  custom_components/tahoma/cover_entities/generic_cover.py
  custom_components/tahoma/cover_entities/vertical_cover.py
Labels: enhancement

#617 Improve support for Domestic Hot Water Production device
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater.py
  custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py
  custom_components/tahoma/climate_devices/atlantic_electrical_towel_dryer.py
  custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/manifest.json
  custom_components/tahoma/sensor.py
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
  requirements.txt
Labels: bug, feature, platform: water_heater

#756 Backport diagnostics from core.
  custom_components/tahoma/diagnostics.py
Labels: feature, backport

#757 add backport label
  .github/pr-labeler.yml
  .github/release-drafter.yml
Labels: Meta: Exclude From Changelog, backport

#755 fix boost mode for CV4E_IO
  custom_components/tahoma/water_heater_devices/domestic_hot_water_production.py
Labels: bug, platform: water_heater

#759 Backport coordinator
  custom_components/tahoma/const.py
  custom_components/tahoma/coordinator.py
Labels: backport

#758 improve gitpod dockerfile
  .gitpod.Dockerfile
  .gitpod.yml
Labels: Meta: Exclude From Changelog

#764 Fix docker image for gitpod
  .gitpod.Dockerfile
  .gitpod.yml
Labels: Meta: Exclude From Changelog

#770 Backport scene
  custom_components/tahoma/scene.py
Labels: backport

#775 Backport light
  custom_components/tahoma/light.py
Labels: backport

#774 Backport switch
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/stateless_exterior_heating.py
  custom_components/tahoma/const.py
  custom_components/tahoma/switch.py
Labels: backport

#771 Backport executor
  custom_components/tahoma/executor.py
Labels: backport

#769 Backport lock
  custom_components/tahoma/lock.py
Labels: backport

#772 Backport button
  custom_components/tahoma/button.py
Labels: backport

#766 Backport number entity
  custom_components/tahoma/number.py
Labels: backport

#765 Backport `binary_sensor` entity
  custom_components/tahoma/binary_sensor.py
  custom_components/tahoma/entity.py
Labels: backport

#773 Backport siren
  custom_components/tahoma/siren.py
Labels: backport

#776 Backport entity
  custom_components/tahoma/entity.py
Labels: backport

#768 Backport `sensor` entity
  custom_components/tahoma/sensor.py
Labels: backport

#767 Backport select entity
  custom_components/tahoma/select.py
Labels: backport

#778 Backport constants
  custom_components/tahoma/const.py
Labels: backport

#779 Add missing constants
  custom_components/tahoma/const.py
  custom_components/tahoma/manifest.json
  requirements.txt
Labels: backport

#777 Refactor Alarm Control Panel
  custom_components/tahoma/alarm_control_panel.py
  custom_components/tahoma/alarm_entities/__init__.py
  custom_components/tahoma/alarm_entities/alarm_panel_controller.py
  custom_components/tahoma/alarm_entities/my_fox_alarm_controller.py
  custom_components/tahoma/alarm_entities/stateful_alarm_controller.py
  custom_components/tahoma/alarm_entities/tsk_alarm_controller.py
  custom_components/tahoma/const.py
Labels: enhancement

#763 Reintroduce low speed feature
  custom_components/tahoma/cover.py
  custom_components/tahoma/cover_entities/vertical_cover.py
Labels: platform: cover, breaking

#783 Bump pyoverkiz (fix Rexel models and typo in setVentilationMode)
  custom_components/tahoma/manifest.json
  requirements.txt
Labels: bug
