Repository iMicknl/ha-tahoma, pull requests merged in 2022-01, with the labels that each got.

#699 Keep retrying on Bad Credentials, instead of reauth flow
  custom_components/tahoma/coordinator.py
Labels: bug

#712 Fix stop button
  custom_components/tahoma/cover_devices/tahoma_cover.py
Labels: bug

#711 Backport core changes to coordinator, upgrade to pyoverkiz 1.1.1
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
  requirements.txt
  tests/test_config_flow.py
Labels: enhancement

#717 Add support for ZeroConf discovery
  custom_components/tahoma/config_flow.py
  custom_components/tahoma/manifest.json
  requirements_test.txt
  tests/test_config_flow.py
Labels: feature

#704 Fix temperature for AtlanticElectricalTowelDryer
  custom_components/tahoma/climate_devices/atlantic_electrical_towel_dryer.py
  custom_components/tahoma/executor.py
Labels: bug

#667 Fix number entity in 2022.1.0dev
  custom_components/tahoma/entity.py
  custom_components/tahoma/number.py
Labels: bug

#715 Bump PyOverkiz and move to Somfy OAuth
  custom_components/tahoma/coordinator.py
  custom_components/tahoma/manifest.json
  requirements.txt
Labels: enhancement

#732 Bump pyoverkiz to 1.3.1
  custom_components/tahoma/manifest.json
  requirements.txt
Labels: bug

#703 Add support for SomfyHeatingTemperatureInterface
  custom_components/tahoma/climate.py
  custom_components/tahoma/climate_devices/somfy_heating_temperature_interface.py
  custom_components/tahoma/const.py
  custom_components/tahoma/number.py
  custom_components/tahoma/select.py
Labels: feature

#733 Rename integration to show the difference with core
  README.md
  custom_components/tahoma/manifest.json
  hacs.json
Labels: enhancement

#734 Don't load integration if core integration is configured
  custom_components/tahoma/__init__.py
Labels: enhancement
